### PR TITLE
Updates to VM image

### PR DESCRIPTION
**Pull request by sualeh**

### CODE REVIEW

**Comment by sualeh** [comment]
@sehrope  - please take a look.

**Comment by sualeh** [comment]
@sehrope - any thoughts on the pull request?

**Comment by sehrope** [comment]
I merged in a reworded version of this into master. I also removed the references to the VM ip addresses as that is not necessary. With port forwarding in the Vagrantfile the ports on localhost will automatically redirect to the VM's private IP address so the default in build.properties in pgjdbc will work.

**Comment by sualeh** [comment]
Thanks, @sehrope - I will give it one more try

**Pull request closed without merging**
